### ISSUE TITLE
Query::filter_by does not allow `IN` filtering

### ISSUE THREAD

**Issue by jeje-ch** [threatify/arango-orm#100]
Here is the actual code:
```
def filter_by(self, _or=False, prepend_rec_name=True, **kwargs):
        """Filter the results by keywords"""
        if not kwargs:
            return self

        condition = " AND ".join(["$REC.{0}==@{0}".format(k) for k in kwargs])
        if len(kwargs) > 1:
            condition = "({0})".format(condition)
        
        return self.filter(
            condition,
            _or=_or,
            prepend_rec_name=False,
            rec_name_placeholder="$REC",
            **kwargs
        )
```

and here my proposal (it supposes you give the "kwarg" on which you want a IN filtering as a list):
```
def filter_by(self, _or=False, prepend_rec_name=True, **kwargs):
        """Filter the results by keywords"""
        if not kwargs:
            return self

        conditions = []
        for k, v in kwargs.items():
            if isinstance(v, list):
                conditions.append("$REC.{0} IN @{0}".format(k))
            else:
                conditions.append("$REC.{0}==@{0}".format(k))

        condition = " AND ".join(conditions)
        if len(kwargs) > 1:
            condition = "({0})".format(condition)

        return self.filter(
            condition,
            _or=_or,
            prepend_rec_name=False,
            rec_name_placeholder="$REC",
            **kwargs
        )
```

Let's say you have a class `Vehicle` with a property `state` ( an int from 0 to 10) and you want the vehicle with `state` 1, 5 and 7.
You can then use `self.db.query(Vehicle).filter_by(state=[1,5,7])`

**Comment by kashifpk** [comment]
@jeje-ch - Thank you for the PR. But this raises another issue, what if state is actually a list and you want to compare using = operator? You can still use the `filter` method instead of `filter_by` and have the IN operator there. Something like:

```python
db.query(Vehicle).filter("rec.state IN [1,5,7]")]
```
If we always assume that list as a value in kwargs implies we want to use the IN operator then we will not have any way of directly comparing actual list values.

**Comment by jeje-ch** [comment]
Oh! right! Didn't think about list comparison (with `=`)

In such case, yes I've to deal with the `filter` method... or we could (open question) add a `comparison_operator` argument (defaulting to `==`) to the `filter_by` method. Allowed operators would be constants and we could then have also `LIKE` or any other comparison operator
