### ISSUE TITLE
Support For Async Execution

### ISSUE THREAD

**Issue by SoundsSerious** [threatify/arango-orm#102]
Does Arango-ORM support async execution? 

The following could be an issue for some threaded applications with Batch Operations.
https://docs.python-arango.com/en/main/threading.html?highlight=thread

It seems inspecting the python-arango api that this would require creating a new Database Class with async methods and support for Arango Jobs.

**Comment by kashifpk** [comment]
Currently it does not. If there is a good design proposal then work can be done on it.

**Comment by SoundsSerious** [comment]
Threads work fine enough for me now, just curious. Feel free to close this issue, dont want to backlog the project too bad :)
