### ISSUE TITLE
Object mapping and inherited classes not mapping well.

### ISSUE THREAD

**Issue by valentingregoire** [threatify/arango-orm#112]
Suppose you have class diagram `A->B->C`. So `C` inherits from `B` and `B` inherits from `A`. If you have a dictionary which you would like to map to an object with ArangoORM, one would typically call the `_load()` method like so: `C._load(json_data)`. However, it seems that since version `0.7.0`, the mapping is screwed and sometimes you receive object of type `A`, sometimes it maps to type `B` and sometimes it does map to `C`. There is no consistency to me for now on how this happens and why. This even happens if I have data in my `json_data` object that has fields that are only present in class `C`. Anyone an idea of what could be going on? It seems that so far, on my end, version `0.6.2` doesn't show this behavior.

**Comment by kashifpk** [comment]
@valentingregoire - can you post some sample code to reproduce this issue? It's fine if it requires a few code runs for the issue to appear. I can use that to look into the cause.

**Comment by valentingregoire** [comment]
Since I can't share my code, I have tried recreating this issue with a very simple base test setup:

```python
from arango_orm import Collection
from arango_orm.fields import String
from db import DB


class A(Collection):
    __collection__ = "some_collection"
    field1 = String()


class B(A):
    field2 = String()


class C(B):
    field3 = String()


document = DB().aql.execute("for d in some_collection limit 1 return d").next()

obj = C._load(document)

print(type(obj))
```
Note that the `DB()` call is just an implementation so that I receive an `arango_orm.Database` instance.

Output:
```output
<class '__main__.C'>
```

Sadly, with this very simple setup, the reproduction of this error dit **not** get recreated. Maybe if you add a more complex data structure things could be reproducible. I suppose we can close this ticket for now until I run into it again, then I'll try to add a more specific example.
