### ISSUE TITLE
Consideration of `Collection._allow_extra_fields=False` as default

### ISSUE THREAD

**Issue by wonderbeyond** [threatify/arango-orm#22]
Allowing extra model properties to be loaded, dumped **and also saved into DB** makes a big confusion before I realized `Collection._allow_extra_fields=False` is required. I've been involved into this issue several times.

When a model has extra properties(defined by `@property`), you cannot prevent them from saving into DB with 
`Collection._allow_extra_fields=True`.

Why not disallow extra fields always (or as default)?

**Comment by kashifpk** [comment]
@wonderbeyond - The rationale for having _allow_extra_fields was that collections are not the same as tables and having the ability to have different data in different documents of a collection is part of the attraction of noSQL. So if we want more table like behavior we set _allow_extra_fields to False.

However @property methods that we don't want to store into the DB are a valid concern here. Perhaps we should have mechanism of specifying names to ignore during dump and load? for load we have the _safe_list class attribute that prevents names present in _safe_list from being overwritten by data from the collection. 

We could either have a similar ignore list or a decorator used alongwith @property, something like:

```python
@no_save
@property
def my_prop(self):
    pass
```

Looking forward to your thoughts on this.

**Comment by wonderbeyond** [comment]
> having the ability to have different data in different documents of a collection

Even so, we can always define a full set of all possible fields, some documents' some field may be null.
Allowing saving arbitrary object attributes into db is dangerous and makes our program behaviour unpredictable.

I prefer to disallow saving extra fields. However if you think it necessary, Can we introduce `Collection._implicit_fields`, in which are extra attributes will be dumped and saved into db.

```python
class Person(Collection):
    _implicit_fields = ['is_adult', 'some_dynamic_attr']

    name = String(required=True, allow_none=False)
    age = Integer(missing=None)

    @property
    def is_adult(self):
        return self.age and self.age >= 18

p = Person(name='wonder', age=20, some_dynamic_attr='test')
```

**Comment by kashifpk** [comment]
Yes using _implicit_fields seems more suitable to me as we still get the extra fields flexibility if any body needs it. Though this requires updating the _implicit_fields attribute for each @property method we define but implementation-wise it's simpler
