### ISSUE TITLE
Any plain to support python-arango 4.0.1?

### ISSUE THREAD

**Issue by whuxujiyuan** [threatify/arango-orm#40]

**Comment by kashifpk** [comment]
yes definitely. Will need to look into the breaking changes in python-arango 4.0.1 and update the code accordingly. PRs are also welcome BTW :-)

**Comment by whuxujiyuan** [comment]
Just had a simple look on python-arango 4.0.1
To run orm on 4.0.1, just needs to change the Database superclass from Database to StandardDatabase, and the graph edge definition change the format to 
```
{
                'edge_collection': relation_obj.__collection__,
                'from_vertex_collections': from_col_names,
                'to_vertex_collections': to_col_names
}
```
Not sure if it has any other big changes

**Comment by kashifpk** [comment]
Fixed for python-arango 4.x - @whuxujiyuan  You can pull from github for the time being. I'll push to pypi in a few hours after testing it with a couple of projects.
