### ISSUE TITLE
Nested Fields

### ISSUE THREAD

**Issue by GamalielMasters** [threatify/arango-orm#43]
In your examples, all members of collections are simple primitive python types like string or integer or are types for which you have a specific field (such as date-time). How do you nest another object instance, (or an array of instances) as a field within a collection?

For example, in my Customer class I have a list of Address objects, which I want to be stored within my arrango document under the key "address":

{
  "username": "Bobby Joe",
  "address": [
    {
      "street": "123 Anywhere",
      "city": "New York",
      "state": "NY",
      "zipcode": "12345"
    },
    {
      "street": "PO BOX 12544",
      "city": "New York",
      "state": "NY",
      "zipcode": "12346"
    }
  ]
}

I know that in Marshmallow, you can nest one schema as a field of another schema using fields.Nested(), so that one schema appears as a data item of another document

However, if I do this within a collection by creating a marshmallow schema for the nested object, and using fields.Nested, arrango-orm creates the correct structure when persisting, but when loading the record back in, the nested object becomes a python dictionary (because there is no link to my domain class for it).

How do I set up my collection to support object instances within it?

**Comment by GamalielMasters** [comment]
I discovered that a working solution to this problem is to provide the marshmallow defined post_load decorated method for converting to a domain object as documented in [Deserializing to Objects](https://marshmallow.readthedocs.io/en/latest/quickstart.html#deserializing-to-objects) _(Head slapping moment)_.  However, I am still interested in if there is built-in support for this in arango-orm, or a recommended way to achieve this result without dropping down to marshmallow land (since marshmallow seems to be more of an implementation detail at this point) and may be a candidate for removal according to #32.

**Comment by kashifpk** [comment]
So far no work has been done on removing marshmallow. While in principle I agree with #32 but at this time putting in the effort to decouple marshmallow is not possible for me. Though with the declarative style usage it is now easier to decouple marshmallow and perhaps use another solution or build one ourselves for data serialization but that would just achieve the same results as marshmallow.

What you could do is to write a test case for the nested fields solution you have and submit a PR. I'll add that test case to the project so even if later we remove marshmallow; we will make sure to keep the nested fields functionality working.
