### ISSUE TITLE
Cannot install webargs alongside because of marshmallow version dependency

### ISSUE THREAD

**Issue by soderluk** [threatify/arango-orm#44]
Is the version `marshmallow~=2.10.0` mandatory?
I'm trying to install `webargs` alongside with `arango-orm` but it requires `marshmallow>=2.15.0` which leads to unresolvable dependencies.

Is it possible to change the marshmallow version dependency?

**Comment by kashifpk** [comment]
@soderluk sorry for getting back to you so late. The version isn't mandatory but I haven't tested it with latest marshmallow. You're welcome to use the code with latest version of marshmallow.

**Comment by soderluk** [comment]
I'm not sure I understand. Arango-orm defines the marshmallow version as `marshmallow~=2.10.0` which makes it impossible to use higher versions. If it works, could it be changed to be `marshmallow>=2.10.0`?

**Comment by kashifpk** [comment]
I meant cloning the repo and updating the version. I just tried arango-orm with the latest marshmallow version and all the tests pass. So updating requirements to marshmallow>=2.10.0.

version 0.4.1 of arango-orm pushed to pypi.

**Comment by soderluk** [comment]
Awesome! Thank you for the work you're doing!
