### ISSUE TITLE
After updating a relation, the _object_from and _object_to is not set

### ISSUE THREAD

**Issue by soderluk** [threatify/arango-orm#47]
I'm updating a relation (edge) with `db.update(relationModel)`, set the `_from` and `_to` to be the id's of two vertices, and that works nicely. After the update I'd like to access the `relationModel._object_from` and `relationModel._object_to`, but they're `None` after the update.
I'd expect the update operation to fill in these values, as they are after loading them from the database.

**Comment by kashifpk** [comment]
You got the relation object via graph.expand? The _object_to and _object_from attributes are only available when doing graph.expand. After the update are you using the return value of the update?

Perhaps you can post code for this scenario?

**Comment by soderluk** [comment]
When using graph.expand it works, but I'd expect to be able to access them also when just running `db.update(model)`. The return value of the update operation only contains the _id, _key, _rev information, if I don't give the `return_new=True` parameter.
I'd like to be able to use the updated model as I'd use it when expanding the graph as well. The code I'm using, is just that, `db.update(model)` and `model.to_dict()` which will convert the attributes to a response.
