### ISSUE TITLE
AQL query does not work when returning vertex

### ISSUE THREAD

**Issue by soderluk** [threatify/arango-orm#49]
When running an AQL query against a graph, I get `KeyError: 'vertices'`, query I'm using:
`FOR v, e, p IN 1..2 ANY 'collection/_key' GRAPH 'graph' RETURN v`
The error occurs in `_objectify_results(results)`:
```
for p_dict in results:
    for v_dict in p_dict['vertices']:
```
The `p_dict` is a dictionary for the model I'm searching for. It only contains the model attributes, nothing in regards to vertices or edges.

I think the AQL function should also support returning a list of vertex/edge models instead of always relying on returning the path.

**Comment by kashifpk** [comment]
Yes we only process the path info for now.

> I think the AQL function should also support returning a list of vertex/edge models instead of always relying on returning the path.

Sure. It might take me some time to get to resolving this. In the mean time PRs are welcome :-)
