### ISSUE TITLE
[Question] How to traverse vertices with only inbound relations?

### ISSUE THREAD

**Issue by soderluk** [threatify/arango-orm#50]
I have a graph with three vertices, (User) -> (User Group) -> (App)

I'm trying to get a result by expanding (or AQL) so that the start node is the (App), and get all the connected vertices in the path, including the User, but I only get the (User Group) vertex information.
The code:
```
relations = vertex.expand(direction, depth) <- function returns the vertex._relations['relations'].
result = [
    rel._next.to_dict() for rel in relations  <- Returns the model attributes as a dictionary.
]
```
Is there any way I can get ALL the vertices connected to the (App) vertex, even if they're inbound links?

**Comment by kashifpk** [comment]
All three types supported by AQL are also supported here. 
[AQL Graph Traversal](https://docs.arangodb.com/3.3/AQL/Graphs/Traversals.html#working-with-named-graphs)

ANY|INBOUND|OUTBOUND

In your case you should try specifiying 'INBOUND' as the direction.

**Comment by soderluk** [comment]
Yes, I used `inbound` here, but my understanding of how the results are returned wasn't complete. The relations are always returned in the _relations['RELATION_NAME'] list, so we'd need to recursively loop through the relation list for the _next object as well.
