### ISSUE TITLE
TypeError: _load() got an unexpected keyword argument 'only'

### ISSUE THREAD

**Issue by soderluk** [threatify/arango-orm#51]
In commit https://github.com/threatify/arango-orm/commit/6236eff46394e02c5dd8408f16382b229812ed27 @wonderbeyond added support for the parameter `only`, but this is not reflected in the `Relation._load()` function, which in turn now raises a `TypeError`:
```
Traceback (most recent call last):
  File "/.venv/api-3xq5-S2D/lib/python3.6/site-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/.venv/api-3xq5-S2D/lib/python3.6/site-packages/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/src/api/app/controllers.py", line 385, in list
    links = self._service.find_all_by(_filter)
  File "/src/api/app/services.py", line 222, in find_all_by
    return q.all()
  File "/.venv/api-3xq5-S2D/lib/python3.6/site-packages/arango_orm/query.py", line 216, in all
    ret.append(self._CollectionClass._load(rec, only=only, db=self._db))
TypeError: _load() got an unexpected keyword argument 'only'
```

**Comment by kashifpk** [comment]
Can you check with fetching the current code from master? The argument is supported and working.

**Comment by soderluk** [comment]
Downloading the latest release from pypi (https://pypi.org/project/arango-orm/0.5.1/#files) and checking the files; the `only` parameter in the `Relation._load()` function is missing.

**Comment by kashifpk** [comment]
Version 0.5.2 pushed to pypi.

Yes I use pip-tools. Never got around to using pipenv and now thinking that is was for good.

Please install updated version and check.

**Comment by soderluk** [comment]
Still not implemented. Downloading the source from pypi.org I get zipped `arango-orm-4.0` folder, and the Relation class' _load() function still doesn't have the `only` parameter.
Updated the library locally as well from pypi, and same thing.
I see it in the master branch in the repository, but not in pypi.

**Comment by kashifpk** [comment]
https://pypi.org/project/arango-orm/

You should see version 0.5.2 here. That is the latest version. We never have a 4.0 version. If it's 0.4 then it's quite old. The file is in wheel format so you'll need to have python wheel installed.

**Comment by soderluk** [comment]
I see version 0.5.2 there, but the download link in pypi points to https://github.com/threatify/arango-orm/archive/v4.0.tar.gz

**Comment by soderluk** [comment]
Installed with `pip install arango-orm==0.5.2`:
```
    @classmethod
    def _load(cls, in_dict, instance=None, db=None):
```
It's just not there. I checked the wheel file as well, and missing from there too.

Also the Download-link on the left side of the pypi page points to https://github.com/threatify/arango-orm/archive/v4.0.tar.gz which is probably wrong.

**Comment by kashifpk** [comment]
aah yes that link is from setup.py file and quite old. Fixed and new version uploaded. You can download from pypi or github's releases section now or install via pip.

**Comment by soderluk** [comment]
I'm sorry, but checking the latest version wheel in pypi is still missing the parameter:
```
    @classmethod
    def _load(cls, in_dict, instance=None, db=None):
```
Could you check the actual code that you upload to pypi? Now when I look at the master branch, the `only` parameter is missing from the Relation._load(), and I can't find the commit that removed it.

**Comment by kashifpk** [comment]
Oh yes you're right we don't have it for Relations, only for collections. I'll add it for relations and push a newer version.

**Comment by soderluk** [comment]
Awesome, thanks! Because the query.all() uses `ret.append(self._CollectionClass._load(rec, only=only, db=self._db))`, where the _CollectionClass can be either a Collection or Relation.

**Comment by soderluk** [comment]
@kashifpk Any idea when this might be implemented?

**Comment by kashifpk** [comment]
Fixed and latest code pushed both to pypi and github. v0.5.3 

Thank you @soderluk for catching this.
