### ISSUE TITLE
Use of __collection__ violates PEP8

### ISSUE THREAD

**Issue by ravenoak** [threatify/arango-orm#54]
As per PEP8 specifications, the `__collection__` variable in `Collection` declarations should be renamed to something else e.g. `__collection` (which would invoke namespace mangling, if that is desired) or `_collection`.

> \_\_double_leading_and_trailing_underscore__: "magic" objects or attributes that live in user-controlled namespaces. E.g. \_\_init__, \_\_import__ or \_\_file__. Never invent such names; only use them as documented.

https://www.python.org/dev/peps/pep-0008/#descriptive-naming-styles

**Comment by kashifpk** [comment]
Yes you are correct. This is an oversight at my part. Will add a deprecation warning for this and use a better name in next version.

**Comment by ravenoak** [comment]
Let me know if there is anything I can do to assist if need be.
