### ISSUE TITLE
`super(self.__class__)` breaks my use case

### ISSUE THREAD

**Issue by wonderbeyond** [threatify/arango-orm#55]
see https://www.reddit.com/r/Python/comments/qa6g7/any_reason_not_to_use_self_class_with_super/

I've made a subclass of `arango_orm.Database` in my project, so I encountered this kind of bug after fetch the latest version of arango-orm.

**Comment by kashifpk** [comment]
Thanks @wonderbeyond - I should have noticed that sub classing Database would cause issues .

**Comment by soderluk** [comment]
@kashifpk: When is this expected to be released? I've got the same problem, and using the latest version 0.5.7 this is still an issue.

**Comment by kashifpk** [comment]
@soderluk - 0.5.8 pushed to pypi. Sorry for the delay.
