### ISSUE TITLE
Include relations in aql query

### ISSUE THREAD

**Issue by RaymondCarlaw** [threatify/arango-orm#57]
When writing a new query, it is possible to specify the return fields, but that is the limit.

It would be beneficial to have the flexibility to include relations (with the source/target vertex) and the depth of the traversal, when querying collections.

This can be done with a graph, though the required records must first be retrieved and then expanded, which is inefficient. 

As a design suggestion, could a new method be added to the Query class that allows for specifying relations to include, and the depth of the traversal?

**Comment by kashifpk** [comment]
something like:

```python
recs = db.query(Area).graph_include([Students, Teachers]).all()
```

If it's ok to still access the linked data as `recs[0]._relations['resides_in'][0]._next.name` then it's relatively easy to do. We cannot include these as object attributes directly as we have to take care about any attributes present in the edges (relations) too.

For a single document for example, we could also have syntax like:

```python
recs = university_graph.expand(db.query(Area).by_key('gotham'), [Students, Teachers])
```

Potential issues I see are that a database can have multiple graphs, some collections might belong to one graph and others to another. So without specifying graph to use for `expand` we would need to lookup for the collection's existence in all existing graphs. Which although possible is a more expensive operation.

**Comment by RaymondCarlaw** [comment]
I was thinking something closer to:

`recs = db.query(Area).expand([AdjacentTo], [Area], 2).all()`

Where expands arguments are:
1. List of Relations
2. List of Collections
3. Depth

The returned objects would contain the relations just as if it were expanded by the graph.

The issue with this is that there may be some result overlap between the base query and the graph traversal. This would result in a single collection document becoming separate objects. This may be solved with some sort of object cache though.

**Comment by rpocase** [comment]
I could definitely use this feature. I wanted to use Graph.aql to find second level relations (i.e. `FOR v,e,p in 1..2 ...`), but found that It only seems to expand the first edge found. As is, I'll either need to run two queries or drop directly to python-arango's AQL.
