### ISSUE TITLE
Nested document

### ISSUE THREAD

**Issue by langju** [threatify/arango-orm#58]
Hi !

I am just trying to play with arango-orm but i'm facing an issue.
Maybe i am doing thing wrong and would like some recommendations :

I have this:

from arango_orm.fields import String, Date, Nested
from arango_orm import Collection, Relation, Graph, GraphConnection
from arango_orm.references import relationship, graph_relationship
from datetime import datetime

class Department(Collection):
    __collection__ = 'department'
    _index = [{'type': 'hash', 'unique': False, 'fields': ['name']}]
    _key = String(required=True)  # registration number
    name = String(required=True, allow_none=False)
    # employees = relationship(__name__ + ".Employee", '_key', target_field='department_key')
    # dob = Date()

class Role(Collection):
    __collection__ = 'role'
    _index = [{'type': 'hash', 'unique': False, 'fields': ['name']}]
    _key = String(required=True)  # registration number
    name = String(required=True, allow_none=False)

    # employees = relationship(__name__ + ".Employee", '_key', target_field='role_key')
    # dob = Date()

class Employee(Collection):
    __collection__ = 'employee'
    _index = [{'type': 'hash', 'unique': False, 'fields': ['name']}]
    _key = String(required=True)  # registration number
    name = String(required=True, allow_none=False)
    #department_key = String()
    #role_key = String()
    hired_on = Date(default=datetime.now)
    department = Nested(Department)
    role = Nested(Role)

what i am trying to do is to have relation, or nested document in arangodb.In the collection employee i should see a role and a department for each employee.

here is how i fill datas;

what am i doing wrong ?

from models_aDB import Department, Employee, Role
from arango import ArangoClient
from arango_orm import Database

#Arango
client = ArangoClient(protocol='http', host='172.18.0.12', port=8529)

def init_arangodb():
    dev_db = client.db('dev', username='xxx', password='yyyyy*', verify=True)
    db = Database(dev_db)

    if not db.has_collection('department'):
        db.create_collection('department')

    if not db.has_collection('employee'):
        db.create_collection('employee')

    if not db.has_collection('role'):
        db.create_collection('role')

    # create the fixture
    engineering = Department(name='engineering',)

    db.add(engineering)

    hr = Department(name='Human Resources')
    db.add(hr)

    manager = Role(name='manager')
    db.add(manager)

    engineer = Role(name='engineer')
    db.add(engineer)

    peter = Employee(name='Peter')
    peter.role = engineer
    peter.department = engineering
    db.add(peter)

    roy = Employee(name='Roy')
    roy.department = engineering
    roy.role = engineer
    db.add(roy)

    tracy = Employee(name='Tracy')
    tracy.role = manager
    tracy.department = hr
    db.add(tracy)

Thanks for your help

**Comment by kashifpk** [comment]
You can do this either using relationships `arango_orm.references.relationship` or if you were making a graph then this could also be done using graph connections. For your case relationship seems more suitable.

Using nested objects in this case creates duplicates of those objects in the DB. I assume that you don't want that. So you don't need to assign the nested objects manually like you're doing here:

```python
peter.role = engineer
peter.department = engineering
```

Instead you define the relationship in the Employee collection. For this you need a field to link to and target collection and target field. For example you could have:

```python
from arango_orm.references import relationship

class Employee(Collection):
    __collection__ = 'employee'
    _index = [{'type': 'hash', 'unique': False, 'fields': ['name']}]
    _key = String(required=True) # registration number
    name = String(required=True, allow_none=False)
    department_key = String()
    role_key = String()
    hired_on = Date(default=datetime.now)
    department = relationship(Department, 'department_key')
    role = relationship(Role, 'role_key')
```

Then for any employee you just need to provide `department_key` and `role_key` and you should be able to access the `department` and `role` documents.

```python
engineering = Department(name='engineering',)

db.add(engineering)

hr = Department(name='Human Resources')
db.add(hr)

manager = Role(name='manager')
db.add(manager)

engineer = Role(name='engineer')
db.add(engineer)

peter = Employee(name='Peter', role_key=engineer._key, department_key=engineering._key)
db.add(peter)

print(peter.role.name)
print(peter.department.name)
```

**Comment by langju** [comment]
thanks for your time and your help !
