### ISSUE TITLE
Add "exclude" arg in _dump method

### ISSUE THREAD

**Issue by overbost** [threatify/arango-orm#65]
I check the source and this is not implemented the "exclude" arg in _dump method, equivalent in marshmallow dump()
Is a common case exclude only few sensibil data

**Comment by wonderbeyond** [comment]
There's already an alternative "only" parameter.

**Comment by overbost** [comment]
> There's already an alternative "only" parameter.

Of course, i know, but if you have a lot of entries, "exclude" can be better and more readable, without forget entries
Marshmallow have this
