### ISSUE TITLE
Remove key from Dict field

### ISSUE THREAD

**Issue by overbost** [threatify/arango-orm#66]
This perform a right update, because all value of user.address is changed
`user.address = "value"`
`db.update(value)`

But if user.addresses is a Dict value, if i remove a key and perform an update, the key will not deleted in db
`user.addresses.pop("home")`
`db.update(user)`

the same happen if i do this
`user.addresses = {}`
`db.update(user)`

i can work around like that but is not the right way
`user.adresses = None`
`db.update(user)`
`user.addresses = {"home: {"street": "my street"}}`
`db.update(user)`

**Comment by soderluk** [comment]
You need to make the addresses a nested property, e.g.
```
class Addresses(Schema):
    home: Dict()

class User:
    addresses = Nested(Addresses)
```

Hope this helps. You may need to play around a bit, but this is how we got our nested dictionaries work with the `db.update()`.

**Comment by overbost** [comment]
Thank you! It works with some customs, and forget the "get by key" features of dictionaries :(
Before i implemented it in this way:
addresses = Dict(default={})
in db
addresses = {
"home": {"street", "city", ...},
"office": {"street", "city", ...},
}
with custom title like "home" or "office", and retrive it simply by key: addresses["home"]

now i must find if there is in list, to know if i must add or update an entry
addresses = List(Nested(Address), default=[])
def getAddressIndex(self, title):
        return next((i for i, addr in enumerate(self.addresses) if addr["title"] == title), None)
