### ISSUE TITLE
How can I use the `or` operator with brackets?

### ISSUE THREAD

**Issue by valentingregoire** [threatify/arango-orm#67]
I have a case like this:
```aql
for c in collection
filter
    c.a == "a" and
    c.b == "b" and
    c.c == "c" and
    c.d == "d" and
    (c.expires >= 5 or c.expires == null)
```

I am fully aware of the `_or` parameter. However, this results in a query without brackets so returning me everything with all my filtering OR just everything that has `null` as value for the field `expires`:
```aql
for c in collection
filter
    c.a == "a" and
    c.b == "b" and
    c.c == "c" and
    c.d == "d" and
    c.expires >= 5 or
    c.expires == null
```

How can I solve this problem? I can't use the filter by because that function only allows for the `==` operator. Perhaps we should be allowed to deliver a list of operators as well?

Thanks!

**Comment by valentingregoire** [comment]
I have solved the issue by hacking it a bit like this:

```python
return db.query(MyObject)
    .filter("a==@a", a="a")
    .filter("b==@b", b="b")
    .filter("c==@c", c="c")
    .filter("d==@d", d="d")
    .filter("(rec.e==null OR rec.e >= @e)", prepend_rec_name=False, e="5")
    .all()
```

This is a very inconvenient approach if you ask me. Also, if in the future you decide to rename the default record variable name, my `rec.` will not work anymore. I am aware of the `rec_name_placeholder`, but that doesn't seem to work, also it's not documented here.

**Comment by kashifpk** [comment]
Given your use case perhaps using `db.aql.execute` directly would be easier? To get proper objects back you can use it in conjunction with `_load`

```python
students = [Student._load(s) for s in db.aql.execute("FOR st IN students RETURN st")]
```

**Comment by valentingregoire** [comment]
@kashifpk, that indeed is an option to solve this, however, I don't like this approach for a couple of reasons:
* The reason of using an ORM, is not to use queries again.
* The `_load` method starts with a single `_`. This means that it is "private/internal" by convention. I must admit, I use it quite regularly since this framework doesn't support too much out of the box when you go really special.
