### ISSUE TITLE
Fields aren't being validated

### ISSUE THREAD

**Issue by ThatFatArcus** [threatify/arango-orm#70]
For some reason, it appears that fields aren't being validated when pushed to the database, as per the schema. Am I missing something here?
```python3
from arango_orm import Collection
from arango_orm.fields import String, Date
from arango import ArangoClient
from arango_orm import Database
from datetime import date

class Student(Collection):
    __collection__ = 'students'
    # _index = [{'type': 'hash', fields: ['name'], unique:False}]
    _key = String(required=True, allow_none=False)  # registration number
    name = String(required=True, allow_none=False)
    dob = Date()

client = ArangoClient(hosts='http://localhost:8529')
test_db = client.db('test', username='root', password='root')
db = Database(test_db)
db.drop_collection(Student)
db.create_collection(Student)

s = Student(name=777, dob=date(year=2016, month=9, day=12))
db.add(s)
print(s._id)
```
Running the following code generates the following DB object:
```
{
    "_id": "students/<random_key_generated_by_arango>", // `required` argument is broken.
    "_key": "<random_key_generated_by_arango>",
    "name": "777", // `int` implicitly converted to String
    "dob": "2016-09-12"
}
```

Is this intended?

Thanks in advance :)

Update:
Even the following fails to raise a ValidationError:
```python3
s = Student(_key=None, name=None, dob=date(year=2016, month=9, day=12))
db.add(s)
print(s._id)
```
And creates the following object:
```
{
    "_id": "students/<random_key_generated_by_arango>",
    "_key": "<random_key_generated_by_arango>",
    "name": null,
    "dob": "2016-09-12"
}
```

**Comment by kashifpk** [comment]
```python
s = Student(_key=None, name=None, dob=date(year=2016, month=9, day=12))
db.add(s)
print(s._id)
```

_key being None is ok as it would get auto-generated if None, however name should have been validated. Thank you for reporting, will check and get back to you.

**Comment by kashifpk** [comment]
Yes the problem is that validation is being done by marshmallow behind the scenes and by default  it is only done when loading data.

"Validation occurs on deserialization but not on serialization. To improve serialization performance, data passed to Schema.dump() are considered valid."

So when inserting the data we get no error but when we try to load the data again we get the SerializationError from marshmallow. So yes this is a bug that needs to be fixed.

**Comment by kashifpk** [comment]
Fixed at github, now validation is done during _dump (which is using during add, update etc) too. New version on pypi will be launched after a few more changes.
