### ISSUE TITLE
expand and discriminator mapping

### ISSUE THREAD

**Issue by jeje-ch** [threatify/arango-orm#78]
Let's say we have a simple graph with people and vehicles and an owning relation between them
```
# entities
class Person(Collection):
    __collection__ = 'person'

    firstname = String(required=True)
    lastname = String(required=True)

class Vehicle(Collection)
    __collection__ = 'vehicle'

    brand = String(required=True)
    model = String(required=True)

# relationship
class Own(Relation):
    __collection__ = 'own'

# graph
class Ownership(Graph):
    __graph__ = 'ownership'

    graph_connections = [
        GraphConnection(Person, Own, Vehicle)
    ]
```
Here, expand will work as expected, letting me retrieve instances of `Vehicle` when I expand an instance of `Person`.

Now, if I use inheritance for Vehicle:
```
# entities
class Person(Collection):
    __collection__ = 'person'

    firstname = String(required=True)
    lastname = String(required=True)

class Vehicle(Collection)
    __collection__ = 'vehicle'

    discr = String(required=True)
    brand = String(required=True)
    model = String(required=True)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.cls = self.__class__.__name__

class Car(Vehicle):
    foo = String(required=True)

class Truck(Vehicle):
    bar = String(required=True)
```

- Using the same `graph_connections` as before, I get instances of `Vehicle` instead of instances of `Car` or `Truck`
- Changing it into `GraphConnection(Person, Own, [Car, Truck])` give me only instances of `Car`

In the meantime, I use that workaround (quick and dirty):
```
# graph
class Ownership(Graph):
    __graph__ = 'ownership'

    graph_connections = [
        GraphConnection(Person, Own, Vehicle)
    ]

    # added method to handle my discriminator mapping
    def _resolve_collection_class(self, col_name: str, doc_dict: dict = None):
        if col_name == 'vehicle':
            if doc_dict['discr'] == 'Car':
                return Car
            if doc_dict['discr'] == 'Truck':
                return Truck

        # default case
        return self.vertices[col_name]

    # overrided method
    def _doc_from_dict(self, doc_dict):
        "Given a result dictionary, creates and returns a document object"

        col_name = doc_dict['_id'].split('/')[0]
        CollectionClass = self._resolve_collection_class(col_name, doc_dict)  # here is the override

        # remove empty values
        keys_to_del = []
        for k, v in doc_dict.items():
            if doc_dict[k] is None:
                keys_to_del.append(k)

        if keys_to_del:
            for k in keys_to_del:
                del doc_dict[k]

        return CollectionClass._load(doc_dict)
```

Is there an already handled way to describe a such graph / discriminator mapping ? or is it planned to be implemented ?

I've various idea to implement it

**Comment by kashifpk** [comment]
I never got around to using inherited model classes so this was never tested. If you have an implementation idea then PR is welcome. This is definitely something we should handle.

**Comment by jeje-ch** [comment]
Ok, nice... then I will

btw: I think the problem comes only if we store inheritance in a unique table (as described above), using separate tables should already work.. but will confirm that also and document it in the PR

**Comment by kashifpk** [comment]
TODO: Add documentation for this feature before pushing a new version to pypi.

**Comment by jeje-ch** [comment]
Thank you @kashifpk ! I didn't imagine a so quick merge, without comment/suggestion to handle :-)

About documentation, I figure it out today... but you went faster than me.

Having another suggestion, I will add that documentation on a dedicated commit in that new PR if you agree

**Comment by kashifpk** [comment]
Yes I actually looked over the code, ran the tests and confirmed that things were working and just merged. As long as existing code isn't broken, we can always expand upon this feature. Yes a new PR for documentation sounds fine.

**Comment by jeje-ch** [comment]
Documentation added in #81

**Comment by kashifpk** [comment]
Thanks.
