### ISSUE TITLE
Support for arango views

### ISSUE THREAD

**Issue by rpocase** [threatify/arango-orm#86]
It would be helpful to have ORM objects for creating and managing Arango Views (currently limited to arangosearch views) and analyzer. Wrapper objects would help avoid needing to use python-arango directly and enable more powerful queries that map results directly to existing ORM objects.

**Comment by kashifpk** [comment]
We can do that. Do you have any possible use cases pseudo code samples in mind?

We would probably want to be able to define view classes (similar to Collection) so we can define and use views from within the orm.

**Comment by rpocase** [comment]
Sorry for the delay. I wanted to wait until I circled back around to where I wanted this functionality again to make sure the context was still fresh.


That's definitely in line with my thinking. I pictured a handful of new Schema type meta classes (`Analzyer`, `View` as a minimum).

This would enable definitions along the lines of the below. Using a mix of metaclass definition and type hinting to convey intent.

```
class SomeCollection(Collection):
  field1 = String(...)
  field2 = String(...)


class MyAnalyzer(Analyzer):
   # avoid dunder mangling, breaking from other collection norms for now
   name = 'my_analyzer'

   stored_values: List[str] = ["field1", "field2"]
   in_background: bool = True


class AnotherAnalyzer(Analyzer):
   ...

class MyView(View):
   # avoid dunder mangling, breaking from other collection norms for now
   name = 'my_view'

   stored_values: List[str] = ["attribute1", "attribute2"]
   in_background: bool = True

   links = [{SomeCollection: [{"field1": [MyAnalyzer],
                              {"field2": [MyAnalyzer, AnotherAnalyzer]
         #alternatively
   links = [Link(SomeCollection, ...)]
```

Theres some nuance here to decide what level of abstraction is too much. 

The ability to search directly via a view would definitely be useful (i.e. `Database.query(MyView)`) and have a great familiarity with Collection searches.
