### ISSUE TITLE
Sort, Limit, & filter order not respected

### ISSUE THREAD

**Issue by RaymondCarlaw** [threatify/arango-orm#91]
It is possible for AQL to use sort, limit and filter and different stages of the query. 
It is not possible with the query builder to create a filter, apply a limit and then apply a secondary filter.

Also, it is not possible to apply multiple FILTER expressions to a query, all conditions are made into one expression, which is not always suitable.

**Comment by kashifpk** [comment]
@RaymondCarlaw - Currently you can also make use of executing raw AQL to build your query. That is supported by the ORM. For example

```python
students = [Student._load(s) for s in db.aql.execute("FOR st IN students RETURN st")]
```

The suggestion itself is nice so I'll keep this issue open to implement this later.

**Comment by RaymondCarlaw** [comment]
Thank you.
I like using the query builder so my work around for now is
`query.filter("field == @value", value=val).filter("true\nFILTER field2 == @value2, value2=val2)`
