### ISSUE TITLE
Filter by date

### ISSUE THREAD

**Issue by ssemenukha** [threatify/arango-orm#94]
Hi there!

I trying to get records in such way
`news = database.query(News).filter("date<=@date", date=date.today()).sort("date DESC").limit(3).all()`

But getting error
`TypeError: Object of type date is not JSON serializable`

How can I filter records by date?

**Comment by kashifpk** [comment]
Hi,

When using filter, you are responsible for properly serializing dates too. 

```python
news = database.query(News).filter("date<=@date", date=date.today().isoformat()).sort("date DESC").limit(3).all()
```

using the `isoformat` method of date objects fixes this query.
