### ISSUE TITLE
batch load suggestions for performance

### ISSUE THREAD

**Issue by priamai** [threatify/arango-orm#95]
Hi there,
I really like this project and would like to learn more about the capability to load large dataset.
I have for example a simple pandas dataframe with the following properties:

- 567033 rows × 3 columns
- Two collections, think of it as teachers-students (where teachers = 6061, students = 10168)
- One relation with one property (an integer count) 

Each day I produce a table and thus I will observe a certain percentage of new students or new teachers, as well as new relations between old teachers new students.

A few challenges:

- The naive load which consists of iterating the dataframe and performing individual add for collection and relation takes an average of 2 hours for each day table
- Is there any difference using the bulk add or is it just an iteration of the add operation?
- I catch exceptions for every add, so if the teacher or the student is already there, I then fetch the original object via key method and then add the new relation, is there some another efficient way to do this?
- Could be that the exceptions are slowing my performance for insertion check?

System:
- Ubuntu 20.04 + Docker
- Octacore Intel + 64 GB RAM + SSD DISK

Thanks a lot in advance.

**Comment by priamai** [comment]
Disclaimer: I am a sinner and have used Neo4J for many years.

**Comment by kashifpk** [comment]
Suggestions from others are welcome. My opinion would be to cache the teacher and student records in memory and do lookup from there instead of from the db on every add request. This should almost double the performance. Also as long as you get data into the DB, you can use the ORM for accessing it. Usually ORMs are not the best mechanism for bulk data loading. You can use `db.bulk_add`  but for that you would need to prepare the data beforehand to ensure no duplicates etc. You can use the `onDuplicate` parameter of the arango bulk import API so you don't need to check for existing records. Ref: https://www.arangodb.com/docs/stable/http/bulk-imports.html

**Comment by priamai** [comment]
Interesting suggestion and also complementing with my experience from Neo4J which seems to be fairly aligned with Arangodb:

- Bulk load nodes first, remove the unique constraints during loading and add them after loading (this does not seem to be possible with Arango e.g. the key field by definition is unique)
- Use cache at runtime as you mentioned move to Redis if is too big
- Add the edges at the end via bulk
- Settings to discard duplicates to avoid time consuming exception handling
 
I will test this and also publish the data with code, I will anonymise it for the benefits of sharing.
Cheers.

**Comment by priamai** [comment]
Hey @kashifpk , I noticed that the bulk_add method was never merged into main.
The reference I could find is [here](https://github.com/threatify/arango-orm/blob/ac9641de37a331e6b33b94ac4a1a60d8557501c8/arango_orm/database.py)

Any plan to add it back to master?

**Comment by kashifpk** [comment]
@priamai It is in master:

https://github.com/threatify/arango-orm/blob/master/arango_orm/database.py#L142

**Comment by robomotic** [comment]
Weird I pulled from master yesterday and was not there. Maybe too tired at night!

**Comment by priamai** [comment]
Okay @kashifpk , how do I pass the extra args?

`db.bulk_add(entity_list=computers,onDuplicate='ignore')`

I get a this Exception:

```
--> 193             res = collection_model.insert_many(entity_dict_list, **kwargs)
    194             for num, entity in enumerate(entity_obj_list, start=0):
    195                 entity._dirty.clear()

TypeError: insert_many() got an unexpected keyword argument 'onDuplicate'

```

**Comment by priamai** [comment]
My bad I just realized the insert_many is from python orm, so I tried this:

`db.bulk_add(entity_list=computers,silent=True,overwrite=True)`

but getting this exception now:

```
---> 26     db.bulk_add(entity_list=computers,silent=True,overwrite=True)
     27     end = datetime.now()
     28     time_taken = end - start

/opt/conda/lib/python3.8/site-packages/arango_orm-0.6.2-py3.8.egg/arango_orm/database.py in bulk_add(self, entity_list, only_dirty, **kwargs)
    194             for num, entity in enumerate(entity_obj_list, start=0):
    195                 entity._dirty.clear()
--> 196                 log.debug(f"{entity} | {res[num]}")
    197                 if not getattr(entity, "_key", None) and "_key" in res[num]:
    198                     setattr(entity, "_key", res[num]["_key"])

TypeError: 'bool' object is not subscriptable
```
