### ISSUE TITLE
delete graph syntax

### ISSUE THREAD

**Issue by priamai** [threatify/arango-orm#96]
Hi there,
what is the ORM correct way to do this:

```
process_graph = TestGraph(connection=db)

if db.has_graph(TestGraph.__graph__):
    print('Deleting Graph')
    db.delete_graph(TestGraph.__graph__)

db.create_graph(process_graph)
```

Also what syntax/API should I use to truncate a Relation collection such as the Relation("studies") in the example?

**Comment by kashifpk** [comment]
Assuming you have a graph object.

```python
db.drop_graph(graph_obj, drop_collections=True)
```

This will drop the graph and all the collections. If you want to keep the collections set drop_collections to False.

https://github.com/threatify/arango-orm/blob/master/arango_orm/database.py#L379

For truncating a collection you can use the underlying python arango API as it is not directly supported at the ORM level atm.

```python
db._db.collection(MyCollectionClass.__collection__).truncate()
```

**Comment by priamai** [comment]
Brilliant, thanks!
By the way do you host the documentation on readthedocs? Would be nice to have it somewhere easy to access.

**Comment by kashifpk** [comment]
I am working on the documentation but it isn't done yet. Initial version is here: https://arango-orm.readthedocs.io/en/latest/

Will be updating and adding to this as time permits.
