### ISSUE TITLE
Support for upsert (i.e. add-or-update?

### ISSUE THREAD

**Issue by scottrbrtsn** [threatify/arango-orm#98]
I don't see an implementation of upsert (add-or-update, update/insert).  Can upsert functionality be added underneath `add()`, or have a `save()` added which does both?

https://stackoverflow.com/questions/7165998/how-to-do-an-upsert-with-sqlalchemy

Mongoengine also supports this.
```
save(force_insert=False, validate=True, clean=True, write_concern=None, cascade=None, cascade_kwargs=None, _refs=None, save_condition=None, signal_kwargs=None, **kwargs)
Save the Document to the database. If the document already exists, it will be updated, otherwise it will be created. Returns the saved object instance.
```

http://docs.mongoengine.org/apireference.html#documents

**Comment by kashifpk** [comment]
May be you're looking for this?

https://github.com/threatify/arango-orm/blob/master/arango_orm/database.py#L109

**Comment by scottrbrtsn** [comment]
Aha!  this looks like it.  Thanks.  Other ORMs just allow for both on save or add, while this is different it looks to be just as good.  Thanks.
